### ISSUE TITLE
Anonymous reply only

### ISSUE THREAD

**Issue by NightHawk2007** [Synic-dx/Little-Lemon#1]
Is this code correct?

<!DOCTYPE html>
<html>
<head>
	<title>Book Store Website</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="styles.css"> 
</head>
<body>
	
	<header>
		<h1>Book Store Website</h1>
		<nav>
			<ul>
				<li><a href="#home">Home</a></li>
				<li><a href="#about">About Us</a></li>
				<li><a href="#contact">Contact Us</a></li>
				<li><a href="#cart">Cart (0)</a></li>
			</ul>
		</nav>
	</header>
	
	
	<section id="hero">
		<h2>Welcome to our Book Store!</h2>
		<p>Explore our vast collection of books and discover new titles.</p>
		<button>Start Shopping</button>
	</section>
	
	
	<section id="featured-books">
		<h2>Featured Books</h2>
		<ul>
			<li>
				<img src="book1.jpg" alt="Book 1">
				<h3>Book 1 Title</h3>
				<p>Book 1 Description</p>
				<button>Add to Cart</button>
			</li>
			<li>
				<img src="book2.jpg" alt="Book 2">
				<h3>Book 2 Title</h3>
				<p>Book 2 Description</p>
				<button>Add to Cart</button>
			</li>
			<li>
				<img src="book3.jpg" alt="Book 3">
				<h3>Book 3 Title</h3>
				<p>Book 3 Description</p>
				<button>Add to Cart</button>
			</li>
		</ul>
	</section>
	
	<section id="categories">
		<h2>Browse by Category</h2>
		<ul>
			<li><a href="#">Fiction</a></li>
			<li><a href="#">Non-Fiction</a></li>
			<li><a href="#">Biography</a></li>
			<li><a href="#">Self-Help</a></li>
		</ul>
	</section>
	
	
	<section id="about">
		<h2>About Us</h2>
		<p>We are a team of book lovers dedicated to bringing you the best selection of books.</p>
	</section>
	
	
	<section id="contact">
		<h2>Contact Us</h2>
		<p>Get in touch with us:</p>
		<ul>
			<li><a href="mailto:info@bookstore.com">info@bookstore.com</a></li>
			<li><a href="tel:+1234567890">+1234567890</a></li>
			<li><a href="#">Address: 123 Main St, Anytown, USA</a></li>
		</ul>
	</section>
	
	
	<footer>
		<p>&copy; 2023 Book Store Website</p>
	</footer>
	
	
	<div id="cart-modal">
		<h2>Cart</h2>
		<ul>
			
		</ul>
		<button>Checkout</button>
	</div>
	
	<script src="script.js"></script> 
</body>
</html>

**Comment by NightHawk2007** [comment]
Send (#) If concerned about safety. No more Help then.

**Comment by Synic-dx** [comment]
its alright

**Comment by NightHawk2007** [comment]
Its alright bro?

**Comment by NightHawk2007** [comment]
Ty

**Comment by NightHawk2007** [comment]
I dare not say much more. Comprehend?

I wonder how to style it with CSS. Any ideas?

**Comment by Synic-dx** [comment]
try and find ig; closing this lol this shit's not for chatting
